# Generated by Django 4.0.3 on 2022-03-18 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supers', '0002_rename_type_super_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='super',
            old_name='super_type',
            new_name='super_type_id',
        ),
    ]
